{
 "title": "Factory Monitor",
 "time": { "from": "2026-03-22T02:19:31.349Z", "to": "2026-03-22T14:19:31.349Z" },
 "refresh": "auto",
 "panels": [
  { "title": "Machine 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "canvas", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 } },
  {
   "title": "OEE — Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine4\")\r\n  |> map(fn: (r) => ({_value: r.availability, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Production Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine4\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine4\")\r\n  |> map(fn: (r) => ({_value: r.downtime, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine4\")\r\n  |> map(fn: (r) => ({_value: r.temperature, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Production count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine4\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))"
    }
   ]
  },
  { "title": "Machine 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  { "type": "canvas", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 27 } },
  {
   "title": "OEE — Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine3\")\r\n  |> map(fn: (r) => ({_value: r.availability, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Production Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine3\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine3\")\r\n  |> map(fn: (r) => ({_value: r.downtime, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine3\")\r\n  |> map(fn: (r) => ({_value: r.temperature, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Production count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine3\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))"
    }
   ]
  },
  { "title": "Machine 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  { "type": "canvas", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 53 } },
  {
   "title": "OEE — Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine2\")\r\n  |> map(fn: (r) => ({_value: r.availability, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Production Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine2\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine2\")\r\n  |> map(fn: (r) => ({_value: r.downtime, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine2\")\r\n  |> map(fn: (r) => ({_value: r.temperature, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Production count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine2\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))"
    }
   ]
  },
  { "title": "Machine 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  { "type": "canvas", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 79 } },
  {
   "title": "OEE — Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine1\")\r\n  |> map(fn: (r) => ({_value: r.availability, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Production Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine1\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine1\")\r\n  |> map(fn: (r) => ({_value: r.downtime, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine1\")\r\n  |> map(fn: (r) => ({_value: r.temperature, _time: r._time}))"
    }
   ]
  },
  {
   "title": "Production count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"machine_data\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"machine_status\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.machine_id == \"machine1\")\r\n  |> map(fn: (r) => ({_value: r.production_count, _time: r._time}))"
    }
   ]
  }
 ]
}